version: 0.2

env:
  parameter-store:
     pushuser: "/r.lerch.org/user"
     pushpass: "/r.lerch.org/pass"
     deploykey: "/github/ungoogled-chromium/deploy_key"
phases:
  pre_build:
    commands:
      - echo Logging into r-push.lerch.org...
      - echo $pushpass | docker login -u $pushuser --password-stdin r-push.lerch.org
      - echo done
      - echo Getting latest version
      - export VERSION=$(curl -s "https://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Buster/amd64/" | grep -oP 'ungoogled-chromium_([0-9.-]).*?\.buster1_amd64\.deb' |grep -oe '[-0-9.]*' |head -2 |tail -1)
      - export VERSION=${VERSION%?}
  build:
    commands:
      - docker build --build-arg VERSION=$VERSION -t r-push.lerch.org/ungoogled-chromium:$VERSION .
      - echo "r.push.lerch.org/ungoogled-chromium:$VERSION" > repo.txt
      - echo "$VERSION" > version.txt
  post_build:
    commands:
      - echo Build Completed on `date`
      - echo Pushing the Docker image...
      - docker push r-push.lerch.org/ungoogled-chromium:$VERSION
      - echo Done
artifacts:
  files:
     - version.txt
     - repo.txt
  name: $(date +%Y-%m-%d)-$VERSION
